package ai

import (
	"context"
	"time"

	"github.com/LesterCerioli/AI-Agent-Go/internal/core/domain"
	"github.com/LesterCerioli/AI-Agent-Go/internal/core/ports"
)

type mockAIClient struct{}

func NewMockAIClient() ports.AIClient {
	return &mockAIClient{}
}

func (m *mockAIClient) AnalyzeAndArchitect(ctx context.Context, prompt string) (*domain.ProjectArchitecture, error) {

	time.Sleep(2 * time.Second)

	return &domain.ProjectArchitecture{
		TechStack: "Go, Fiber, PostgreSQL",
		Language:  "Go",
		Structure: `{"cmd": {"main.go": ""}, "internal": {}}`,
	}, nil
}

func (m *mockAIClient) GenerateCode(ctx context.Context, architecture *domain.ProjectArchitecture) ([]domain.GeneratedFile, error) {

	time.Sleep(3 * time.Second)

	return []domain.GeneratedFile{
		{
			FilePath: "cmd/main.go",
			Content: `package main

import "fmt"

func main() {
	fmt.Println("Generated by Mock AI Engine")
}`,
		},
		{
			FilePath: "README.md",
			Content:  "# Generated Project\n\nThis project was generated by the AI Engine.",
		},
	}, nil
}
